# Generated by Django 3.2.8 on 2022-03-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PriceTrackerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gameID',
            field=models.IntegerField(default=0, max_length=255),
        ),
    ]
