# Generated by Django 3.2.8 on 2022-03-02 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PriceTrackerApp', '0002_game_gameid'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='digitalStore',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='physicalStore',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='gameID',
            field=models.IntegerField(default=0),
        ),
    ]
