# Generated by Django 4.0.2 on 2022-03-03 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PriceTrackerApp', '0002_game_gameid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gameID',
            field=models.IntegerField(default=0),
        ),
    ]
