# Generated by Django 3.2.8 on 2022-03-20 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PriceTrackerApp', '0003_alter_game_gameid'),
        ('PriceTrackerApp', '0003_auto_20220302_2120'),
    ]

    operations = [
    ]
