# Generated by Django 3.2.8 on 2022-03-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PriceTrackerApp', '0005_auto_20220321_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='idnum',
            field=models.IntegerField(default=0, max_length=5),
        ),
    ]
