# Generated by Django 3.2.8 on 2022-03-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PriceTrackerApp', '0006_profile_idnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='idnum',
            field=models.IntegerField(default=0),
        ),
    ]
