# Generated by Django 3.2.8 on 2022-03-30 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PriceTrackerApp', '0007_alter_profile_idnum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='idnum',
        ),
    ]
